{
  "comments": [
    {
      "key": {
        "uuid": "a1586fff_162e84bd",
        "filename": "event_log.py",
        "patchSetId": 8
      },
      "lineNbr": 104,
      "author": {
        "id": 1004651
      },
      "writtenOn": "2017-12-13T10:58:04Z",
      "side": 1,
      "message": "This call to add is sending the parameters in the wrong order.\n\nsignature is:\n\nAdd(self, name, task_name, start, finish\u003dNone, success\u003dNone, try_count\u003d1, kind\u003d\u0027RepoOp\u0027)\n\nso the sync events will get a switched task_name and success",
      "revId": "e0684addeeb920ddf83168d5fbbbe50cb9287abd",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": true
    }
  ]
}