{
  "comments": [
    {
      "key": {
        "uuid": "ed55e939_9755c424",
        "filename": "subcmds/forall.py",
        "patchSetId": 2
      },
      "lineNbr": 211,
      "author": {
        "id": 1002883
      },
      "writtenOn": "2015-05-13T17:34:56Z",
      "side": 1,
      "message": "Why is the creation of this pool moved inside the try?",
      "range": {
        "startLine": 211,
        "startChar": 29,
        "endLine": 211,
        "endChar": 33
      },
      "revId": "f693aeb61d04225234da9ab0fff90d2d46da3db2",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    }
  ]
}